### ISSUE TITLE
referencing self in run_orig in RasRunner

### ISSUE THREAD

**Issue by jacob-a-brown** [mikebannis/rascontrol#2]
If one writes a function to run rascontrol, rather than make a global variable of rascontrol, one runs into a referencing error. In run_orig in RasRunner, I changed

`self.full_xs_list = rc.simple_xs_list()`
`self.rivers = {x.river for x in rr.full_xs_list}`
`self.xs_by_river = [[x for x in rr.full_xs_list if x.river == riv] for riv in self.rivers]`

to

`self.full_xs_list = rc.simple_xs_list()`
`self.rivers = {x.river for x in self.full_xs_list}`
`self.xs_by_river = [[x for x in self.full_xs_list if x.river == riv] for riv in self.rivers]`

to fix the problem.

**Comment by mikebannis** [comment]
This relates to another project not rascontrol
