### ISSUE TITLE
Cannot import RasController

### ISSUE THREAD

**Issue by SayanDey1991** [mikebannis/rascontrol#9]
I installed rascontrol through git and pip as described in the rascontrol homepage. When I run the following code (given in basic usage example), it gives me the error: module 'rascontrol' has no attribute 'RasController'

>>> import rascontrol
>>> rc = rascontrol.RasController(version='507')

I am using Python 3.7.6 and HEC-RAS 5.0.7

**Comment by beenjammin** [comment]
Worked fine for me on 5.07, although I just stored the rascontrol.py file locally rather than installing with git/pip

**Comment by gutzbenj** [comment]
@SayanDey1991 would you please post the exact error code? or has the problem resolved?
